### ISSUE TITLE
fimImpressao

### ISSUE THREAD

**Issue by aemsoftwarearacatuba** [PaoloDooM/gpos720_printer#2]
Conforme conversei com o pessoal da Gertec, o fimImpressao so deve ser chamado quando terminar de enviar todos os comandos de impressao. Vi que vc esta chamando a cada comando. Como sujestão, deixaria esse como parametrizavel.

**Comment by PaoloDooM** [comment]
Oi!! Sim, a biblioteca da Gertec está projetada para enviar o fimImpressao apenas no final de todos os comandos de impressão, mas em meus testes identifiquei que, dependendo da quantidade de comandos, ela acaba ignorando alguns. Por isso, decidi incluir o fimImpressao após cada chamada. Não sei se isso se deve a algum erro na biblioteca GEDIS ou a alguma limitação de buffer. Ainda assim, posso adicionar o parâmetro na próxima versão. Obrigado pela sugestão.

**Comment by PaoloDooM** [comment]
Na versão 1.2.0, adicionei ao construtor do plugin o parâmetro booleano `finalizarImpressao`, que determina se o método `fimImpressao` será chamado após a execução dos comandos de impressão. Por padrão, este parâmetro será `false`, então você precisará chamar `fimImpressao` após executar os comandos de impressão.

**Comment by aemsoftwarearacatuba** [comment]
Provavelmente é limitação de buffer.


Enviado do Email para Windows

De: Paolo Bufalino
Enviado:terça-feira, 6 de agosto de 2024 09:37
Para: PaoloDooM/gpos720_printer
Cc:AeM Software; Author
Assunto: Re: [PaoloDooM/gpos720_printer] fimImpressao (Issue #2)

Oi!! Sim, a biblioteca da Gertec está projetada para enviar o fimImpressao apenas no final de todos os comandos de impressão, mas em meus testes identifiquei que, dependendo da quantidade de comandos, ela acaba ignorando alguns. Por isso, decidi incluir o fimImpressao após cada chamada. Não sei se isso se deve a algum erro na biblioteca GEDIS ou a alguma limitação de buffer. Ainda assim, posso adicionar o parâmetro na próxima versão. Obrigado pela sugestão.
